# docker-compose.yml
version: "3.8"
services:

  strapiexample:
    image: strapi/strapi
    container_name: strapiexample
    restart: unless-stopped
    #env_file: environment.env
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_NAME=strapi
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
    depends_on:
      - mongo
      - mongo-express
    #    links:
    #      - mongo:mongo
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"

  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - strapi-app-network
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
      - strapidata:/data/db

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - strapi-app-network
    ports:
      - "8081:8081"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
